import pandas as pd

# Paises, regiones, provincias, comunas, y pueblos se entregarán
# como clave -> valor para poder hallar más facilmente el nombre

def paises():
    return {
        2  : 'África',
        5  : 'Sudamérica',
        9  : 'Oceanía',
        10 : 'Antártida',
        12 : 'Argelia',
        13 : 'Centroamérica',
        21 : 'Norteamérica',
        29 : 'Caribe',
        32 : 'Argentina',
        36 : 'Australia',
        40 : 'Austria',
        51 : 'Armenia',
        56 : 'Bélgica',
        68 : 'Bolivia (Estado Plurinacional de)',
        76 : 'Brasil',
        96 : 'Brunei Darussalam',
        100: 'Bulgaria',
        124: 'Canadá',
        136: 'Islas Caimán',
        142: 'Asia',
        150: 'Europa',
        156: 'China',
        158: 'Taiwán (provincia de China)',
        170: 'Colombia',
        188: 'Costa Rica',
        191: 'Croacia',
        192: 'Cuba',
        203: 'República Checa',
        208: 'Dinamarca',
        214: 'República Dominicana',
        218: 'Ecuador',
        222: 'El Salvador',
        246: 'Finlandia',
        250: 'Francia',
        258: 'Polinesia Francesa',
        275: 'Palestina (Estado de)',
        276: 'Alemania',
        300: 'Grecia',
        320: 'Guatemala',
        332: 'Haití',
        340: 'Honduras',
        348: 'Hungría',
        356: 'India',
        360: 'Indonesia',
        364: 'Irán (República Islámica de)',
        372: 'Irlanda',
        376: 'Israel',
        380: 'Italia',
        392: 'Japón',
        400: 'Jordania',
        410: 'Corea del Sur (República de)',
        422: 'Líbano',
        484: 'México',
        504: 'Marruecos',
        524: 'Nepal',
        528: 'Países Bajos',
        548: 'Vanuatu',
        554: 'Nueva Zelandia',
        558: 'Nicaragua',
        578: 'Noruega',
        586: 'Pakistán',
        591: 'Panamá',
        600: 'Paraguay',
        604: 'Perú',
        608: 'Filipinas',
        616: 'Polonia',
        620: 'Portugal',
        626: 'Timor-Leste',
        630: 'Puerto Rico',
        642: 'Rumania',
        643: 'Rusia (Federación de)',
        688: 'Serbia',
        710: 'Sudáfrica',
        724: 'España',
        752: 'Suecia',
        756: 'Suiza',
        760: 'República Árabe Siria',
        764: 'Tailandia',
        792: 'Turquía',
        804: 'Ucrania',
        818: 'Egipto',
        826: 'Reino Unido de Gran Bretaña e Irlanda del Norte',
        840: 'Estados Unidos de América',
        858: 'Uruguay',
        862: 'Venezuela (República Bolivariana de)',
        997: 'País no declarado',
        998: 'No aplica',
        999: 'Missing'
    }

def regiones():
    return {
        15 : {'region' : 'Arica y Parinacota', 'codigo_region15r' : 15},
        1 :  {'region' : 'Tarapacá', 'codigo_region15r' : 1},
        2 :  {'region' : 'Antofagasta', 'codigo_region15r' : 2},
        3 :  {'region' : 'Atacama', 'codigo_region15r' : 3 },
        4 :  {'region' : 'Coquimbo', 'codigo_region15r' : 4 },
        5 :  {'region' : 'Valparaíso', 'codigo_region15r' : 5 },
        6 :  {'region' : 'Región del Libertador Gral. Bernardo O’Higgins', 'codigo_region15r' : 6 },
        7 :  {'region' : 'Región del Maule', 'codigo_region15r' : 7 },
        8 :  {'region' : 'Región del Biobío', 'codigo_region15r' : 8 },
        9 :  {'region' : 'Región de la Araucanía', 'codigo_region15r' : 9 },
        14 : {'region' : 'Región de Los Ríos', 'codigo_region15r' : 14 },
        10 : {'region' : 'Región de Los Lagos', 'codigo_region15r' : 10 },
        11 : {'region' : 'Región Aisén del Gral. Carlos Ibáñez del Campo', 'codigo_region15r' : 11 },
        12 : {'region' : 'Región de Magallanes y de la Antártica Chilena', 'codigo_region15r' : 12 },
        13 : {'region' : 'Región Metropolitana de Santiago', 'codigo_region15r' : 13 },
        16 : {'region' : 'Región de Ñuble', 'codigo_region15r' : 8 }
    }

def provincias():
   return {
        151 : {'provincia' : 'Arica', 'codigo_region' : 15 },
        152	: {'provincia' : 'Parinacota', 'codigo_region' : 15},
        11 :  {'provincia' : 'Iquique', 'codigo_region' : 1 },
        14 :  {'provincia' : 'Tamarugal', 'codigo_region' : 1 },
        21 :  {'provincia' : 'Antofagasta', 'codigo_region' : 2 },
        22 :  {'provincia' : 'El Loa', 'codigo_region' : 2 },
        23 :  {'provincia' : 'Tocopilla', 'codigo_region' : 2 },
        31 :  {'provincia' : 'Copiapó', 'codigo_region' : 3 },
        32 :  {'provincia' : 'Chañaral', 'codigo_region' : 3 },
        33 :  {'provincia' : 'Huasco', 'codigo_region' : 3 },
        41 :  {'provincia' : 'Elqui', 'codigo_region' : 4 },
        42 :  {'provincia' : 'Choapa', 'codigo_region' : 4 },
        43 :  {'provincia' : 'Limarí', 'codigo_region' : 4 },
        51 :  {'provincia' : 'Valparaíso', 'codigo_region' : 5},
        52 :  {'provincia' : 'Isla de Pascua', 'codigo_region' : 5 },
        53 :  {'provincia' : 'Los Andes', 'codigo_region' : 5 },
        54 :  {'provincia' : 'Petorca', 'codigo_region' : 5 },
        55 :  {'provincia' : 'Quillota', 'codigo_region' : 5 },
        56 :  {'provincia' : 'San Antonio', 'codigo_region' : 5 },
        57 :  {'provincia' : 'San Felipe de Aconcagua', 'codigo_region' : 5 },
        58 :  {'provincia' : 'Marga Marga', 'codigo_region' : 5 },
        61 :  {'provincia' : 'Cachapoal', 'codigo_region' : 6 },
        62 :  {'provincia' : 'Cardenal Caro', 'codigo_region' : 6 },
        63 :  {'provincia' : 'Colchagua', 'codigo_region' : 6 },
        71 :  {'provincia' : 'Talca', 'codigo_region' : 7 },
        72 :  {'provincia' : 'Cauquenes', 'codigo_region' : 7 },
        73 :  {'provincia' : 'Curicó', 'codigo_region' : 7 },
        74 :  {'provincia' : 'Linares', 'codigo_region' : 7 },
        81 :  {'provincia' : 'Concepción', 'codigo_region' : 8 },
        82 :  {'provincia' : 'Arauco', 'codigo_region' : 8 },
        83 :  {'provincia' : 'Biobío', 'codigo_region' : 8 },
        84 :  {'provincia' : 'Ñuble', 'codigo_region' : 8 },
        91 :  {'provincia' : 'Cautín', 'codigo_region' : 9 },
        92 :  {'provincia' : 'Malleco', 'codigo_region' : 9 },
        141 : {'provincia' : 'Valdivia', 'codigo_region' : 14 },
        142 : {'provincia' : 'Ranco', 'codigo_region' : 14 },
        101 : {'provincia' : 'Llanquihue', 'codigo_region' : 10 },
        102 : {'provincia' : 'Chiloe', 'codigo_region' : 10 },
        103 : {'provincia' : 'Osorno', 'codigo_region' : 10 },
        104 : {'provincia' : 'Palena', 'codigo_region' : 10 },
        111 : {'provincia' : 'Coihaique', 'codigo_region' : 11 },
        112 : {'provincia' : 'Aisén', 'codigo_region' : 11 },
        113 : {'provincia' : 'Capitán Prat', 'codigo_region' : 11 },
        114 : {'provincia' : 'General Carrera', 'codigo_region' : 11 },
        121 : {'provincia' : 'Magallanes', 'codigo_region' : 12 },
        122 : {'provincia' : 'Antártica Chilena', 'codigo_region' : 12 },
        123 : {'provincia' : 'Tierra del Fuego', 'codigo_region' : 12 },
        124 : {'provincia' : 'Última Esperanza', 'codigo_region' : 12 },
        131 : {'provincia' : 'Santiago', 'codigo_region' : 13 },
        132 : {'provincia' : 'Cordillera', 'codigo_region' : 13 },
        133 : {'provincia' : 'Chacabuco', 'codigo_region' : 13 },
        134 : {'provincia' : 'Maipo', 'codigo_region' : 13 },
        135 : {'provincia' : 'Melipilla', 'codigo_region' : 13 },
        136 : {'provincia' : 'Talagante', 'codigo_region' : 13 }
   }

def comunas():
    return {
        15101 :{'comuna' :  'Arica ', 'codigo_provincia' : 151 },
        15102 :{'comuna' :  'Camarones ', 'codigo_provincia' : 151 },
        15201 :{'comuna' :  'Putre ', 'codigo_provincia' : 152 },
        15202 :{'comuna' :  'General Lagos ', 'codigo_provincia' : 152 },
        1101 : {'comuna' :  'Iquique ', 'codigo_provincia' : 11 },
        1107 : {'comuna' :  'Alto Hospicio ', 'codigo_provincia' : 11 },
        1401 : {'comuna' :  'Pozo Almonte ', 'codigo_provincia' : 14 },
        1402 : {'comuna' :  'Camiña ', 'codigo_provincia' : 14 },
        1403 : {'comuna' :  'Colchane ', 'codigo_provincia' : 14 },
        1404 : {'comuna' :  'Huara ', 'codigo_provincia' : 14 },
        1405 : {'comuna' :  'Pica ', 'codigo_provincia' : 14 },
        2101 : {'comuna' :  'Antofagasta ', 'codigo_provincia' : 21 },
        2102 : {'comuna' :  'Mejillones ', 'codigo_provincia' : 21 },
        2103 : {'comuna' :  'Sierra Gorda ', 'codigo_provincia' : 21 },
        2104 : {'comuna' :  'Taltal ', 'codigo_provincia' : 21 },
        2201 : {'comuna' :  'Calama ', 'codigo_provincia' : 22 },
        2202 : {'comuna' :  'Ollagüe ', 'codigo_provincia' : 22 },
        2203 : {'comuna' :  'San Pedro de Atacama ', 'codigo_provincia' : 22 },
        2301 : {'comuna' :  'Tocopilla ', 'codigo_provincia' : 23 },
        2302 : {'comuna' :  'María Elena ', 'codigo_provincia' : 23 },
        3101 : {'comuna' :  'Copiapó ', 'codigo_provincia' : 31 },
        3102 : {'comuna' :  'Caldera ', 'codigo_provincia' : 31 },
        3103 : {'comuna' :  'Tierra Amarilla ', 'codigo_provincia' : 31 },
        3201 : {'comuna' :  'Chañaral ', 'codigo_provincia' : 32 },
        3202 : {'comuna' :  'Diego de Almagro ', 'codigo_provincia' : 32 },
        3301 : {'comuna' :  'Vallenar ', 'codigo_provincia' : 33 },
        3302 : {'comuna' :  'Alto del Carmen ', 'codigo_provincia' : 33 },
        3303 : {'comuna' :  'Freirina ', 'codigo_provincia' : 33 },
        3304 : {'comuna' :  'Huasco ', 'codigo_provincia' : 33 },
        4101 : {'comuna' :  'La Serena ', 'codigo_provincia' : 41 },
        4102 : {'comuna' :  'Coquimbo ', 'codigo_provincia' : 41 },
        4103 : {'comuna' :  'Andacollo ', 'codigo_provincia' : 41 },
        4104 : {'comuna' :  'La Higuera ', 'codigo_provincia' : 41 },
        4105 : {'comuna' :  'Paiguano ', 'codigo_provincia' : 41 },
        4106 : {'comuna' :  'Vicuña ', 'codigo_provincia' : 41 },
        4201 : {'comuna' :  'Illapel ', 'codigo_provincia' : 42 },
        4202 : {'comuna' :  'Canela ', 'codigo_provincia' : 42 },
        4203 : {'comuna' :  'Los Vilos ', 'codigo_provincia' : 42 },
        4204 : {'comuna' :  'Salamanca ', 'codigo_provincia' : 42 },
        4301 : {'comuna' :  'Ovalle ', 'codigo_provincia' : 43 },
        4302 : {'comuna' :  'Combarbalá ', 'codigo_provincia' : 43 },
        4303 : {'comuna' :  'Monte Patria ', 'codigo_provincia' : 43 },
        4304 : {'comuna' :  'Punitaqui ', 'codigo_provincia' : 43 },
        4305 : {'comuna' :  'Río Hurtado ', 'codigo_provincia' : 43 },
        5101 : {'comuna' :  'Valparaíso ', 'codigo_provincia' : 51 },
        5102 : {'comuna' :  'Casablanca ', 'codigo_provincia' : 51 },
        5103 : {'comuna' :  'Concón ', 'codigo_provincia' : 51 },
        5104 : {'comuna' :  'Juan Fernández ', 'codigo_provincia' : 51 },
        5105 : {'comuna' :  'Puchuncaví ', 'codigo_provincia' : 51 },
        5107 : {'comuna' :  'Quintero ', 'codigo_provincia' : 51 },
        5109 : {'comuna' :  'Viña del Mar ', 'codigo_provincia' : 51 },
        5201 : {'comuna' :  'Isla de Pascua ', 'codigo_provincia' : 52 },
        5301 : {'comuna' :  'Los Andes ', 'codigo_provincia' : 53 },
        5302 : {'comuna' :  'Calle Larga ', 'codigo_provincia' : 53 },
        5303 : {'comuna' :  'Rinconada ', 'codigo_provincia' : 53 },
        5304 : {'comuna' :  'San Esteban ', 'codigo_provincia' : 53 },
        5401 : {'comuna' :  'La Ligua ', 'codigo_provincia' : 54 },
        5402 : {'comuna' :  'Cabildo ', 'codigo_provincia' : 54 },
        5403 : {'comuna' :  'Papudo ', 'codigo_provincia' : 54 },
        5404 : {'comuna' :  'Petorca ', 'codigo_provincia' : 54 },
        5405 : {'comuna' :  'Zapallar ', 'codigo_provincia' : 54 },
        5501 : {'comuna' :  'Quillota ', 'codigo_provincia' : 55 },
        5502 : {'comuna' :  'Calera ', 'codigo_provincia' : 55 },
        5503 : {'comuna' :  'Hijuelas ', 'codigo_provincia' : 55 },
        5504 : {'comuna' :  'La Cruz ', 'codigo_provincia' : 55 },
        5506 : {'comuna' :  'Nogales ', 'codigo_provincia' : 55 },
        5601 : {'comuna' :  'San Antonio ', 'codigo_provincia' : 56},
        5602 : {'comuna' :  'Algarrobo ', 'codigo_provincia' : 56},
        5603 : {'comuna' :  'Cartagena ', 'codigo_provincia' : 56},
        5604 : {'comuna' :  'El Quisco ', 'codigo_provincia' : 56},
        5605 : {'comuna' :  'El Tabo ', 'codigo_provincia' : 56},
        5606 : {'comuna' :  'Santo Domingo ', 'codigo_provincia' : 56},
        5701 : {'comuna' :  'San Felipe ', 'codigo_provincia' : 57},
        5702 : {'comuna' :  'Catemu ', 'codigo_provincia' : 57},
        5703 : {'comuna' :  'Llaillay ', 'codigo_provincia' : 57},
        5704 : {'comuna' :  'Panquehue ', 'codigo_provincia' : 57},
        5705 : {'comuna' :  'Putaendo ', 'codigo_provincia' : 57},
        5706 : {'comuna' :  'Santa María ', 'codigo_provincia' : 57},
        5801 : {'comuna' :  'Quilpué ', 'codigo_provincia' : 58 },
        5802 : {'comuna' :  'Limache ', 'codigo_provincia' : 58 },
        5803 : {'comuna' :  'Olmué ', 'codigo_provincia' : 58 },
        5804 : {'comuna' :  'Villa Alemana ', 'codigo_provincia' : 58 },
        6101 : {'comuna' :  'Rancagua ', 'codigo_provincia' : 61},
        6102 : {'comuna' :  'Codegua ', 'codigo_provincia' : 61},
        6103 : {'comuna' :  'Coinco ', 'codigo_provincia' : 61},
        6104 : {'comuna' :  'Coltauco ', 'codigo_provincia' : 61},
        6105 : {'comuna' :  'Doñihue ', 'codigo_provincia' : 61},
        6106 : {'comuna' :  'Graneros ', 'codigo_provincia' : 61},
        6107 : {'comuna' :  'Las Cabras ', 'codigo_provincia' : 61},
        6108 : {'comuna' :  'Machalí ', 'codigo_provincia' : 61},
        6109 : {'comuna' :  'Malloa ', 'codigo_provincia' : 61},
        6110 : {'comuna' :  'Mostazal ', 'codigo_provincia' : 61},
        6111 : {'comuna' :  'Olivar ', 'codigo_provincia' : 61},
        6112 : {'comuna' :  'Peumo ', 'codigo_provincia' : 61},
        6113 : {'comuna' :  'Pichidegua ', 'codigo_provincia' : 61},
        6114 : {'comuna' :  'Quinta de Tilcoco ', 'codigo_provincia' : 61},
        6115 : {'comuna' :  'Rengo ', 'codigo_provincia' : 61},
        6116 : {'comuna' :  'Requínoa ', 'codigo_provincia' : 61},
        6117 : {'comuna' :  'San Vicente ', 'codigo_provincia' : 61},
        6201 : {'comuna' :  'Pichilemu ', 'codigo_provincia' : 62},
        6202 : {'comuna' :  'La Estrella ', 'codigo_provincia' : 62},
        6203 : {'comuna' :  'Litueche ', 'codigo_provincia' : 62},
        6204 : {'comuna' :  'Marchihue ', 'codigo_provincia' : 62},
        6205 : {'comuna' :  'Navidad ', 'codigo_provincia' : 62},
        6206 : {'comuna' :  'Paredones ', 'codigo_provincia' : 62},
        6301 : {'comuna' :  'San Fernando ', 'codigo_provincia' : 63},
        6302 : {'comuna' :  'Chépica ', 'codigo_provincia' : 63},
        6303 : {'comuna' :  'Chimbarongo ', 'codigo_provincia' : 63},
        6304 : {'comuna' :  'Lolol ', 'codigo_provincia' : 63},
        6305 : {'comuna' :  'Nancagua ', 'codigo_provincia' : 63},
        6306 : {'comuna' :  'Palmilla ', 'codigo_provincia' : 63},
        6307 : {'comuna' :  'Peralillo ', 'codigo_provincia' : 63},
        6308 : {'comuna' :  'Placilla ', 'codigo_provincia' : 63},
        6309 : {'comuna' :  'Pumanque ', 'codigo_provincia' : 63},
        6310 : {'comuna' :  'Santa Cruz ', 'codigo_provincia' : 63},
        7101 : {'comuna' :  'Talca ', 'codigo_provincia' : 71 },
        7102 : {'comuna' :  'Constitución ', 'codigo_provincia' : 71 },
        7103 : {'comuna' :  'Curepto ', 'codigo_provincia' : 71 },
        7104 : {'comuna' :  'Empedrado ', 'codigo_provincia' : 71 },
        7105 : {'comuna' :  'Maule ', 'codigo_provincia' : 71 },
        7106 : {'comuna' :  'Pelarco ', 'codigo_provincia' : 71 },
        7107 : {'comuna' :  'Pencahue ', 'codigo_provincia' : 71 },
        7108 : {'comuna' :  'Río Claro ', 'codigo_provincia' : 71 },
        7109 : {'comuna' :  'San Clemente ', 'codigo_provincia' : 71 },
        7110 : {'comuna' :  'San Rafael ', 'codigo_provincia' : 71 },
        7201 : {'comuna' :  'Cauquenes ', 'codigo_provincia' : 72 },
        7202 : {'comuna' :  'Chanco ', 'codigo_provincia' : 72 },
        7203 : {'comuna' :  'Pelluhue ', 'codigo_provincia' : 72 },
        7301 : {'comuna' :  'Curicó ', 'codigo_provincia' : 73 },
        7302 : {'comuna' :  'Hualañé ', 'codigo_provincia' : 73 },
        7303 : {'comuna' :  'Licantén ', 'codigo_provincia' : 73 },
        7304 : {'comuna' :  'Molina ', 'codigo_provincia' : 73 },
        7305 : {'comuna' :  'Rauco ', 'codigo_provincia' : 73 },
        7306 : {'comuna' :  'Romeral ', 'codigo_provincia' : 73 },
        7307 : {'comuna' :  'Sagrada Familia ', 'codigo_provincia' : 73 },
        7308 : {'comuna' :  'Teno ', 'codigo_provincia' : 73 },
        7309 : {'comuna' :  'Vichuquén ', 'codigo_provincia' : 73 },
        7401 : {'comuna' :  'Linares ', 'codigo_provincia' : 74 },
        7402 : {'comuna' :  'Colbún ', 'codigo_provincia' : 74 },
        7403 : {'comuna' :  'Longaví ', 'codigo_provincia' : 74 },
        7404 : {'comuna' :  'Parral ', 'codigo_provincia' : 74 },
        7405 : {'comuna' :  'Retiro ', 'codigo_provincia' : 74 },
        7406 : {'comuna' :  'San Javier ', 'codigo_provincia' : 74 },
        7407 : {'comuna' :  'Villa Alegre ', 'codigo_provincia' : 74 },
        7408 : {'comuna' :  'Yerbas Buenas ', 'codigo_provincia' : 74 },
        8101 : {'comuna' :  'Concepción ', 'codigo_provincia' : 81 },
        8102 : {'comuna' :  'Coronel ', 'codigo_provincia' : 81 },
        8103 : {'comuna' :  'Chiguayante ', 'codigo_provincia' : 81 },
        8104 : {'comuna' :  'Florida ', 'codigo_provincia' : 81 },
        8105 : {'comuna' :  'Hualqui ', 'codigo_provincia' : 81 },
        8106 : {'comuna' :  'Lota ', 'codigo_provincia' : 81 },
        8107 : {'comuna' :  'Penco ', 'codigo_provincia' : 81 },
        8108 : {'comuna' :  'San Pedro de la Paz ', 'codigo_provincia' : 81 },
        8109 : {'comuna' :  'Santa Juana ', 'codigo_provincia' : 81 },
        8110 : {'comuna' :  'Talcahuano ', 'codigo_provincia' : 81 },
        8111 : {'comuna' :  'Tomé ', 'codigo_provincia' : 81 },
        8112 : {'comuna' :  'Hualpén ', 'codigo_provincia' : 81 },
        8201 : {'comuna' :  'Lebu ', 'codigo_provincia' : 82},
        8202 : {'comuna' :  'Arauco ', 'codigo_provincia' : 82},
        8203 : {'comuna' :  'Cañete ', 'codigo_provincia' : 82},
        8204 : {'comuna' :  'Contulmo ', 'codigo_provincia' : 82},
        8205 : {'comuna' :  'Curanilahue ', 'codigo_provincia' : 82},
        8206 : {'comuna' :  'Los Álamos ', 'codigo_provincia' : 82},
        8207 : {'comuna' :  'Tirúa ', 'codigo_provincia' : 82},
        8301 : {'comuna' :  'Los Ángeles ', 'codigo_provincia' : 83},
        8302 : {'comuna' :  'Antuco ', 'codigo_provincia' : 83},
        8303 : {'comuna' :  'Cabrero ', 'codigo_provincia' : 83},
        8304 : {'comuna' :  'Laja ', 'codigo_provincia' : 83},
        8305 : {'comuna' :  'Mulchén ', 'codigo_provincia' : 83},
        8306 : {'comuna' :  'Nacimiento ', 'codigo_provincia' : 83},
        8307 : {'comuna' :  'Negrete ', 'codigo_provincia' : 83},
        8308 : {'comuna' :  'Quilaco ', 'codigo_provincia' : 83},
        8309 : {'comuna' :  'Quilleco ', 'codigo_provincia' : 83},
        8310 : {'comuna' :  'San Rosendo ', 'codigo_provincia' : 83},
        8311 : {'comuna' :  'Santa Bárbara ', 'codigo_provincia' : 83},
        8312 : {'comuna' :  'Tucapel ', 'codigo_provincia' : 83},
        8313 : {'comuna' :  'Yumbel ', 'codigo_provincia' : 83},
        8314 : {'comuna' :  'Alto Biobío ', 'codigo_provincia' : 83},
        8401 : {'comuna' :  'Chillán ', 'codigo_provincia' : 84 },
        8402 : {'comuna' :  'Bulnes ', 'codigo_provincia' : 84 },
        8403 : {'comuna' :  'Cobquecura ', 'codigo_provincia' : 84 },
        8404 : {'comuna' :  'Coelemu ', 'codigo_provincia' : 84 },
        8405 : {'comuna' :  'Coihueco ', 'codigo_provincia' : 84 },
        8406 : {'comuna' :  'Chillán Viejo ', 'codigo_provincia' : 84 },
        8407 : {'comuna' :  'El Carmen ', 'codigo_provincia' : 84 },
        8408 : {'comuna' :  'Ninhue ', 'codigo_provincia' : 84 },
        8409 : {'comuna' :  'Ñiquén ', 'codigo_provincia' : 84 },
        8410 : {'comuna' :  'Pemuco ', 'codigo_provincia' : 84 },
        8411 : {'comuna' :  'Pinto ', 'codigo_provincia' : 84 },
        8412 : {'comuna' :  'Portezuelo ', 'codigo_provincia' : 84 },
        8413 : {'comuna' :  'Quillón ', 'codigo_provincia' : 84 },
        8414 : {'comuna' :  'Quirihue ', 'codigo_provincia' : 84 },
        8415 : {'comuna' :  'Ránquil ', 'codigo_provincia' : 84 },
        8416 : {'comuna' :  'San Carlos ', 'codigo_provincia' : 84 },
        8417 : {'comuna' :  'San Fabián ', 'codigo_provincia' : 84 },
        8418 : {'comuna' :  'San Ignacio ', 'codigo_provincia' : 84 },
        8419 : {'comuna' :  'San Nicolás ', 'codigo_provincia' : 84 },
        8420 : {'comuna' :  'Treguaco ', 'codigo_provincia' : 84 },
        8421 : {'comuna' :  'Yungay ', 'codigo_provincia' : 84 },
        9101 : {'comuna' :  'Temuco ', 'codigo_provincia' : 91 },
        9102 : {'comuna' :  'Carahue ', 'codigo_provincia' : 91 },
        9103 : {'comuna' :  'Cunco ', 'codigo_provincia' : 91 },
        9104 : {'comuna' :  'Curarrehue ', 'codigo_provincia' : 91 },
        9105 : {'comuna' :  'Freire ', 'codigo_provincia' : 91 },
        9106 : {'comuna' :  'Galvarino ', 'codigo_provincia' : 91 },
        9107 : {'comuna' :  'Gorbea ', 'codigo_provincia' : 91 },
        9108 : {'comuna' :  'Lautaro ', 'codigo_provincia' : 91 },
        9109 : {'comuna' :  'Loncoche ', 'codigo_provincia' : 91 },
        9110 : {'comuna' :  'Melipeuco ', 'codigo_provincia' : 91 },
        9111 : {'comuna' :  'Nueva Imperial ', 'codigo_provincia' : 91 },
        9112 : {'comuna' :  'Padre las Casas ', 'codigo_provincia' : 91 },
        9113 : {'comuna' :  'Perquenco ', 'codigo_provincia' : 91 },
        9114 : {'comuna' :  'Pitrufquén ', 'codigo_provincia' : 91 },
        9115 : {'comuna' :  'Pucón ', 'codigo_provincia' : 91 },
        9116 : {'comuna' :  'Saavedra ', 'codigo_provincia' : 91 },
        9117 : {'comuna' :  'Teodoro Schmidt ', 'codigo_provincia' : 91 },
        9118 : {'comuna' :  'Toltén ', 'codigo_provincia' : 91 },
        9119 : {'comuna' :  'Vilcún ', 'codigo_provincia' : 91 },
        9120 : {'comuna' :  'Villarrica ', 'codigo_provincia' : 91 },
        9121 : {'comuna' :  'Cholchol ', 'codigo_provincia' : 91 },
        9201 : {'comuna' :  'Angol ', 'codigo_provincia' : 92 },
        9202 : {'comuna' :  'Collipulli ', 'codigo_provincia' : 92 },
        9203 : {'comuna' :  'Curacautín ', 'codigo_provincia' : 92 },
        9204 : {'comuna' :  'Ercilla ', 'codigo_provincia' : 92 },
        9205 : {'comuna' :  'Lonquimay ', 'codigo_provincia' : 92 },
        9206 : {'comuna' :  'Los Sauces ', 'codigo_provincia' : 92 },
        9207 : {'comuna' :  'Lumaco ', 'codigo_provincia' : 92 },
        9208 : {'comuna' :  'Purén ', 'codigo_provincia' : 92 },
        9209 : {'comuna' :  'Renaico ', 'codigo_provincia' : 92 },
        9210 : {'comuna' :  'Traiguén ', 'codigo_provincia' : 92 },
        9211 : {'comuna' :  'Victoria ', 'codigo_provincia' : 92 },
        14101: {'comuna' :  'Valdivia ', 'codigo_provincia' : 141 },
        14102: {'comuna' :  'Corral ', 'codigo_provincia' : 141 },
        14103: {'comuna' :  'Lanco ', 'codigo_provincia' : 141 },
        14104: {'comuna' :  'Los Lagos ', 'codigo_provincia' : 141 },
        14105: {'comuna' :  'Máfil ', 'codigo_provincia' : 141 },
        14106: {'comuna' :  'Mariquina ', 'codigo_provincia' : 141 },
        14107: {'comuna' :  'Paillaco ', 'codigo_provincia' : 141 },
        14108: {'comuna' :  'Panguipulli ', 'codigo_provincia' : 141 },
        14201: {'comuna' :  'La Unión ', 'codigo_provincia' : 142 },
        14202: {'comuna' :  'Futrono ', 'codigo_provincia' : 142 },
        14203: {'comuna' :  'Lago Ranco ', 'codigo_provincia' : 142 },
        14204: {'comuna' :  'Río Bueno ', 'codigo_provincia' : 142 },
        10101: {'comuna' :  'Puerto Montt ', 'codigo_provincia' : 101 },
        10102: {'comuna' :  'Calbuco ', 'codigo_provincia' : 101 },
        10103: {'comuna' :  'Cochamó ', 'codigo_provincia' : 101 },
        10104: {'comuna' :  'Fresia ', 'codigo_provincia' : 101 },
        10105: {'comuna' :  'Frutillar ', 'codigo_provincia' : 101 },
        10106: {'comuna' :  'Los Muermos ', 'codigo_provincia' : 101 },
        10107: {'comuna' :  'Llanquihue ', 'codigo_provincia' : 101 },
        10108: {'comuna' :  'Maullín ', 'codigo_provincia' : 101 },
        10109: {'comuna' :  'Puerto Varas ', 'codigo_provincia' : 101 },
        10201: {'comuna' :  'Castro ', 'codigo_provincia' : 102 },
        10202: {'comuna' :  'Ancud ', 'codigo_provincia' : 102 },
        10203: {'comuna' :  'Chonchi ', 'codigo_provincia' : 102 },
        10204: {'comuna' :  'Curaco de Vélez ', 'codigo_provincia' : 102 },
        10205: {'comuna' :  'Dalcahue ', 'codigo_provincia' : 102 },
        10206: {'comuna' :  'Puqueldón  ', 'codigo_provincia' : 102 },
        10207: {'comuna' :  'Queilén ', 'codigo_provincia' : 102 },
        10208: {'comuna' :  'Quellón ', 'codigo_provincia' : 102 },
        10209: {'comuna' :  'Quemchi ', 'codigo_provincia' : 102 },
        10210: {'comuna' :  'Quinchao ', 'codigo_provincia' : 102 },
        10301: {'comuna' :  'Osorno ', 'codigo_provincia' : 103 },
        10302: {'comuna' :  'Puerto Octay ', 'codigo_provincia' : 103 },
        10303: {'comuna' :  'Purranque ', 'codigo_provincia' : 103 },
        10304: {'comuna' :  'Puyehue ', 'codigo_provincia' : 103 },
        10305: {'comuna' :  'Río Negro ', 'codigo_provincia' : 103 },
        10306: {'comuna' :  'San Juan de la Costa ', 'codigo_provincia' : 103 },
        10307: {'comuna' :  'San Pablo ', 'codigo_provincia' : 103 },
        10401: {'comuna' :  'Chaitén ', 'codigo_provincia' : 104 },
        10402: {'comuna' :  'Futaleufú ', 'codigo_provincia' : 104 },
        10403: {'comuna' :  'Hualaihué ', 'codigo_provincia' : 104 },
        10404: {'comuna' :  'Palena ', 'codigo_provincia' : 104 },
        11101: {'comuna' :  'Coihaique ', 'codigo_provincia' : 111 },
        11102: {'comuna' :  'Lago Verde ', 'codigo_provincia' : 111 },
        11201: {'comuna' :  'Aisén ', 'codigo_provincia' : 112 },
        11202: {'comuna' :  'Cisnes ', 'codigo_provincia' : 112 },
        11203: {'comuna' :  'Guaitecas ', 'codigo_provincia' : 112 },
        11301: {'comuna' :  'Cochrane ', 'codigo_provincia' : 113 },
        11302: {'comuna' :  'O’Higgins ', 'codigo_provincia' : 113 },
        11303: {'comuna' :  'Tortel ', 'codigo_provincia' : 113 },
        11401: {'comuna' :  'Chile Chico ', 'codigo_provincia' : 114},
        11402: {'comuna' :  'Río Ibáñez ', 'codigo_provincia' : 114},
        12101: {'comuna' :  'Punta Arenas ', 'codigo_provincia' : 121 },
        12102: {'comuna' :  'Laguna Blanca ', 'codigo_provincia' : 121 },
        12103: {'comuna' :  'Río Verde ', 'codigo_provincia' : 121 },
        12104: {'comuna' :  'San Gregorio ', 'codigo_provincia' : 121 },
        12201: {'comuna' :  'Cabo de Hornos (Ex Navarino) ', 'codigo_provincia' : 122},
        12202: {'comuna' :  'Antártica ', 'codigo_provincia' : 122},
        12301: {'comuna' :  'Porvenir ', 'codigo_provincia' : 123 },
        12302: {'comuna' :  'Primavera ', 'codigo_provincia' : 123 },
        12303: {'comuna' :  'Timaukel ', 'codigo_provincia' : 123 },
        12401: {'comuna' :  'Natales ', 'codigo_provincia' : 124 },
        12402: {'comuna' :  'Torres del Paine ', 'codigo_provincia' : 124 },
        13101: {'comuna' :  'Santiago ', 'codigo_provincia' : 131 },
        13102: {'comuna' :  'Cerrillos ', 'codigo_provincia' : 131 },
        13103: {'comuna' :  'Cerro Navia ', 'codigo_provincia' : 131 },
        13104: {'comuna' :  'Conchalí ', 'codigo_provincia' : 131 },
        13105: {'comuna' :  'El Bosque ', 'codigo_provincia' : 131 },
        13106: {'comuna' :  'Estación Central ', 'codigo_provincia' : 131 },
        13107: {'comuna' :  'Huechuraba ', 'codigo_provincia' : 131 },
        13108: {'comuna' :  'Independencia ', 'codigo_provincia' : 131 },
        13109: {'comuna' :  'La Cisterna ', 'codigo_provincia' : 131 },
        13110: {'comuna' :  'La Florida ', 'codigo_provincia' : 131 },
        13111: {'comuna' :  'La Granja ', 'codigo_provincia' : 131 },
        13112: {'comuna' :  'La Pintana ', 'codigo_provincia' : 131 },
        13113: {'comuna' :  'La Reina ', 'codigo_provincia' : 131 },
        13114: {'comuna' :  'Las Condes ', 'codigo_provincia' : 131 },
        13115: {'comuna' :  'Lo Barnechea ', 'codigo_provincia' : 131 },
        13116: {'comuna' :  'Lo Espejo ', 'codigo_provincia' : 131 },
        13117: {'comuna' :  'Lo Prado ', 'codigo_provincia' : 131 },
        13118: {'comuna' :  'Macul ', 'codigo_provincia' : 131 },
        13119: {'comuna' :  'Maipú ', 'codigo_provincia' : 131 },
        13120: {'comuna' :  'Ñuñoa ', 'codigo_provincia' : 131 },
        13121: {'comuna' :  'Pedro Aguirre Cerda ', 'codigo_provincia' : 131 },
        13122: {'comuna' :  'Peñalolén ', 'codigo_provincia' : 131 },
        13123: {'comuna' :  'Providencia ', 'codigo_provincia' : 131 },
        13124: {'comuna' :  'Pudahuel ', 'codigo_provincia' : 131 },
        13125: {'comuna' :  'Quilicura ', 'codigo_provincia' : 131 },
        13126: {'comuna' :  'Quinta Normal ', 'codigo_provincia' : 131 },
        13127: {'comuna' :  'Recoleta ', 'codigo_provincia' : 131 },
        13128: {'comuna' :  'Renca ', 'codigo_provincia' : 131 },
        13129: {'comuna' :  'San Joaquín ', 'codigo_provincia' : 131 },
        13130: {'comuna' :  'San Miguel ', 'codigo_provincia' : 131 },
        13131: {'comuna' :  'San Ramón ', 'codigo_provincia' : 131 },
        13132: {'comuna' :  'Vitacura ', 'codigo_provincia' : 131 },
        13201: {'comuna' :  'Puente Alto ', 'codigo_provincia' : 132 },
        13202: {'comuna' :  'Pirque ', 'codigo_provincia' : 132 },
        13203: {'comuna' :  'San José de Maipo ', 'codigo_provincia' : 132 },
        13301: {'comuna' :  'Colina ', 'codigo_provincia' : 133 },
        13302: {'comuna' :  'Lampa ', 'codigo_provincia' : 133 },
        13303: {'comuna' :  'Tiltil ', 'codigo_provincia' : 133 },
        13401: {'comuna' :  'San Bernardo ', 'codigo_provincia' : 134 },
        13402: {'comuna' :  'Buin ', 'codigo_provincia' : 134 },
        13403: {'comuna' :  'Calera de Tango ', 'codigo_provincia' : 134 },
        13404: {'comuna' :  'Paine ', 'codigo_provincia' : 134 },
        13501: {'comuna' :  'Melipilla ', 'codigo_provincia' : 135 },
        13502: {'comuna' :  'Alhué ', 'codigo_provincia' : 135 },
        13503: {'comuna' :  'Curacaví ', 'codigo_provincia' : 135 },
        13504: {'comuna' :  'María Pinto ', 'codigo_provincia' : 135 },
        13505: {'comuna' :  'San Pedro ', 'codigo_provincia' : 135 },
        13601: {'comuna' :  'Talagante ', 'codigo_provincia' : 136 },
        13602: {'comuna' :  'El Monte ', 'codigo_provincia' : 136 },
        13603: {'comuna' :  'Isla de Maipo ', 'codigo_provincia' : 136 },
        13604: {'comuna' :  'Padre Hurtado ', 'codigo_provincia' : 136 },
        13605: {'comuna' :  'Peñaflor ', 'codigo_provincia' : 136 },
        16101: {'comuna' :  'Chillán', 'codigo_provincia' : 84},
        16102: {'comuna' : 'Bulnes', 'codigo_provincia' : 84},
        16103: {'comuna' : 'Chillán Viejo', 'codigo_provincia' : 84},
        16104: {'comuna' : 'El Carmen', 'codigo_provincia' : 84},
        16105: {'comuna' : 'Pemuco', 'codigo_provincia' : 84},
        16106 :{'comuna' : 'Pinto', 'codigo_provincia' : 84},
        16107: {'comuna' : 'Quillón', 'codigo_provincia' : 84},
        16108: {'comuna' : 'San Ignacio', 'codigo_provincia' : 84},
        16109: {'comuna' : 'Yungay', 'codigo_provincia' : 84},
        16201: {'comuna' : 'Quirihue', 'codigo_provincia' : 84},
        16202: {'comuna' : 'Cobquecura', 'codigo_provincia' : 84},
        16203: {'comuna' : 'Coelemu', 'codigo_provincia' : 84},
        16204: {'comuna' : 'Ninhue', 'codigo_provincia' : 84},
        16205: {'comuna' : 'Portezuelo', 'codigo_provincia' : 84},
        16206 :{'comuna' : 'Ránquil', 'codigo_provincia' : 84},
        16207: {'comuna' : 'Treguaco', 'codigo_provincia' : 84},
        16301: {'comuna' : 'San Carlos', 'codigo_provincia' : 84},
        16302: {'comuna' : 'Coihueco', 'codigo_provincia' : 84},
        16303: {'comuna' : 'Ñiquén', 'codigo_provincia' : 84},
        16304: {'comuna' : 'San Fabián', 'codigo_provincia' : 84},
        16305: {'comuna' : 'San Nicolás', 'codigo_provincia' : 84},
        98 :   {'comuna' :  'No aplica ', 'codigo_provincia' : 99 },
        99 :   {'comuna' :  'Missing ', 'codigo_provincia' : 99 },
        97 :   {'comuna' :  'Comuna no declarada ', 'codigo_provincia' : 99 },
        997 :  {'comuna' :  'Comuna no declarada ', 'codigo_provincia' : 99 },
        998 :  {'comuna' :  'No aplica ', 'codigo_provincia' : 99 },
        999 :  {'comuna' :  'Missing ', 'codigo_provincia' : 99 },
        1000 : {'comuna' : 'Región de Tarapacá', 'codigo_provincia' : 99 },
        2000 : {'comuna' : 'Región de Antofagasta', 'codigo_provincia' : 99 },
        3000 : {'comuna' : 'Región de Atacama', 'codigo_provincia' : 99 },
        4000 : {'comuna' : 'Región de Coquimbo', 'codigo_provincia' : 99 },
        5000 : {'comuna' : 'Región de Valparaíso', 'codigo_provincia' : 99 },
        6000 : {'comuna' : 'Región del Libertador General Bernardo O’Higgins', 'codigo_provincia' : 99 },
        7000 : {'comuna' : 'Región del Maule', 'codigo_provincia' : 99 },
        8000 : {'comuna' : 'Región de Biobío (previo a Región de Ñuble)', 'codigo_provincia' : 99 },
        9000:  {'comuna' : 'Región de La Araucanía', 'codigo_provincia' : 99 },
        10000: {'comuna' : 'Región de Los Lagos', 'codigo_provincia' : 99 },
        11000: {'comuna' : 'Región de Aysén del General Carlos Ibáñez del Campo', 'codigo_provincia' : 99 },
        12000: {'comuna' : 'Región de Magallanes y de la Antártica Chilena', 'codigo_provincia' : 99 },
        13000: {'comuna' : 'Región Metropolitana de Santiago', 'codigo_provincia' : 99 },
        14000: {'comuna' : 'Región de Los Ríos', 'codigo_provincia' : 99 },
        15000: {'comuna' : 'Región de Arica y Parinacota', 'codigo_provincia' : 99 },
        16000: {'comuna' : 'Región de Ñuble', 'codigo_provincia' : 99 }
        
    }

def distritos():
    distritos = []
    for i in range(33):
        distritos.append(i+1)
    distritos.append(99)
    return distritos

def parentesco():
    return {
        1 : 'Jefe/a de hogar',
        2 : 'Esposo/a o cónyuge',
        3 : 'Conviviente por unión civil',
        4 : 'Conviviente de hecho o pareja',
        5 : 'Hijo/a',
        6 : 'Hijo/a del cónyuge, conviviente o pareja',
        7 : 'Hermano/a',
        8 : 'Padre/madre',
        9 : 'Cuñado/a',
        10 : 'Suegro/a',
        11 : 'Yerno/nuera',
        12 : 'Nieto/a',
        13 : 'Abuelo/a',
        14 : 'Otro pariente',
        15 : 'No pariente',
        16 : 'Servicio doméstico puertas adentro',
        17 : 'Persona en vivienda colectiva',
        18 : 'Persona en tránsito',
        19 : 'Persona en operativo calle'
    }

def sexo():
    return { 1 : 'Hombre', 2 : 'Mujer' }

def residencia_habitual():
    return {
        1 : 'En esta vivienda',
        2 : 'En otra vivienda',
        3 : 'En otra comuna',
        4 : 'En otro pais',
        98 : 'No aplica',
        99 : 'Missing'
    }

def residencia_hace_5años():
    return {
        1 : 'Aún no nacía',
        2 : 'En esta comuna',
        3 : 'En otra comuna',
        4 : 'Peru',
        5 : 'Argentina',
        6 : 'Bolivia',
        7 : 'Ecuador',
        8 : 'Colombia',
        9 : 'Otro',
        98 : 'No aplica',
        99 : 'Missing'
    }

def lugar_nacimiento():
    return {
        1 : 'En esta comuna',
        2 : 'En otra comuna',
        3 : 'Perú',
        4 : 'Argentina',
        5 : 'Bolivia',
        6 : 'Ecuador',
        7 : 'Colombia',
        8 : 'Otro',
        98 : 'No aplica',
        99 : 'Missing'
    }

def periodo_llegada():
    return {
        1 : 'Entre 2010 y 2017',
        2 : 'Entre 2000 y 2009',
        3 : 'Entre 1990 y 1999',
        4 : 'Antes de 1990',
        98 : 'No aplica',
        99 : 'Missing'
    }

def estudia():
    return {
        1 : 'Sí',
        2 : 'No asiste actualmente',
        3 : 'Nunca asistió',
        98 : 'No aplica',
        99 : 'Missing'
    }

def nivel_curso_mas_alto_aprobado():
    return {
        1 : 'Sala cuna o jardín infantil',
        2 : 'Prekínder',
        3 : 'Kínder',
        4 : 'Especial o diferencial',
        5 : 'Educación básica',
        6 : 'Primaria o preparatorio (sistema antiguo)',
        7 : 'Científico-humanista',
        8 : 'Técnica profesional',
        9 : 'Humanidades (sistema antiguo)',
        10 : 'Técnica comercial, industrial/normalista (sistema antiguo)',
        11 : 'Técnico superior (1-3 años)',
        12 : 'Profesional (4 o más años)',
        13 : 'Magíster',
        14 : 'Doctorado',
        98 : 'No aplica',
        99 : 'Missing'
    }

def respuesta_booleana():
    return {
        1 : 'Sí',
        2 : 'No',
        98 : 'No aplica',
        99 : 'Missing'
    }

def pueblo_listado():
    return {
        1 : 'Mapuche',
        2 : 'Aymara',
        3 : 'Rapa Nui',
        4 : 'Lican Antai',
        5 : 'Quechua',
        6 : 'Colla',
        7 : 'Diaguita',
        8 : 'Kawésqar',
        9 : 'Yagán o Yamana',
        10 : 'Otro',
        98 : 'No aplica',
        99 : 'Missing'
    }

def pueblo_otro():
    return {
        3 : 'Lafquenche',
        4 : 'Pehuenche',
        5 : 'Huilliche',
        6 : 'Picunche',
        21 : 'Changos',
        22 : 'Chonos',
        23 : 'Ona',
        28 : 'Tehuelches',
        33 : 'Pueblos de América Latina',
        34 : 'Pueblos del resto del mundo',
        35 : 'Afrodescendiente',
        37 : 'Otros pueblos presentes en el territorio nacional',
        97 : 'Pueblo no declarado',
        98 : 'No aplica',
        99 : 'Missing'
    }

def trabajo_semana_pasada():
    return {
        1 : 'Por un pago en dinero o especies',
        2 : 'Sin pago para un familiar',
        3 : 'Tenía empleo pero estuvo de vacaciones, con licencia, en descanso laboral, etc.',
        4 : 'Se encontraba buscando empleo',
        5 : 'Estaba estudiando',
        6 : 'Realizó quehaceres de su hogar',
        7 : 'Es jubilado, pensionado o rentista',
        8 : 'Otra situación',
        98 : 'No aplica',
        99 : 'Missing'
    }

def rama_actividad_economica():
    return {
        'A' : 'Agricultura, ganadería, silvicultura y pesca',
        'B' : 'Explotación de minas y canteras',
        'C' : 'Industrias manufactureras',
        'D' : 'Suministro de electricidad, gas, vapor y aire acondicionado',
        'E' : 'Suministro de agua; evacuación de aguas residuales, gestión de desechos y descontaminación',
        'F' : 'Construcción',
        'G' : 'Comercio al por mayor y al por menor; reparación de vehículos automotores y motocicletas',
        'H' : 'Transporte y almacenamiento',
        'I' : 'Actividades de alojamiento y de servicios de comidas',
        'J' : 'Información y comunicaciones',
        'K' : 'Actividades financieras y de seguros',
        'L' : 'Actividades inmobiliarias',
        'M' : 'Actividades profesionales, científicas y técnicas',
        'N' : 'Actividades de servicios administrativos y de apoyo',
        'O' : 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria',
        'P' : 'Enseñanza',
        'Q' : 'Actividades de atención de la salud humana y de asistencia social',
        'R' : 'Actividades artísticas, de entretenimiento y recreativas',
        'S' : 'Otras actividades de servicios',
        'T' : 'Actividades de los hogares como empleadores; actividades no diferenciadas de los hogares como productores de bienes y servicios para uso propio',
        'U' : 'Actividades de organizaciones y órganos extraterritoriales',
        'Z' : 'Rama no declarada',
        '98' : 'No aplica',
        '99' : 'Missing',
    }

#def curso_mas_alto_aprobado()
#def total_hijos_nacidos_vivos():
#def total_hijos_actualmente_vivos():
#def mes_nacimiento_ultimo_hijo():
#def año_nacimiento_ultimo_hijo():
#def escolaridad():
